extends Node

enum Crew {DALLAS, KANE, RIPLEY, ASH, LAMBERT, PARKER, BRETT}

enum ItemType {CAT_BASKET, FLAMETHROWER}

enum Location {COMMAND_CENTER, CORRIDOR1, INFIRMARY, LABORATORY}

enum MenuMode {NONE, GO_TO}
