extends Node

enum Crew {DALLAS, KANE, RIPLEY, ASH, LAMBERT, PARKER, BRETT}

enum ItemType {CAT_BASKET, FLAMETHROWER}

enum Location {COMMAND_CENTER, CORRIDOR1, INFIRMARY, LABORATORY, CORRIDOR2, CORRIDOR3, CORRIDOR4, CORRIDOR5,
				INF_STORES, ARMOURY, ENGINE_1, CRYO_VAULT, LAB_STORES, STORES_1, ENGINE_2, ENGINE_3}

enum MenuMode {NONE, GO_TO, PICK_UP}
